agent: "DQN"
env: "BreakoutDeterministic-v4"
epsilon_start: 0.5
epsilon_end: 0.1
anneal_period: 1.0e+6
gamma: 0.99
buffer_size: 1.e+6
batch_size: 4
train_episodes: 100000
update_period: 10
eval_period: 100
eval_episodes: 10
max_steps: 10000
burn_in: 10000
