agent: "DQN"
env: "BreakoutDeterministic-v4"
epsilon_start: 1
epsilon_end: 0.1
anneal_period: 1.0e+6
gamma: 0.999
buffer_size: 1.e+6
batch_size: 12
train_episodes: 1000
max_train_steps: 100
update_period: 10
eval_period: 10
eval_episodes: 1
max_eval_steps: 100
