agent: "DQN"
env: "PongDeterministic-v4"
epsilon_start: 1.0
epsilon_end: 0.1
anneal_period: 1.0e+6
gamma: 0.99
buffer_size: 1.e+5
batch_size: 32
train_episodes: 100000
update_period: 10000
eval_period: 10000
eval_episodes: 10
max_steps: 10000
burn_in: 5000
